apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::629228315510:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17SF4MTIKUO72
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::629228315510:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T12:45:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "14167"
  uid: de469277-31aa-4b32-8b22-d0b188a2c8c0
